# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sessionset.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sessionset.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x10sessionset.proto\"*\n\x11SMFSessionRequest\x12\x15\n\rsubscriber_id\x18\x01 \x01(\t\"+\n\x12UPFSessionResponse\x12\x15\n\rsubscriber_id\x18\x01 \x01(\t2=\n\tPipelined\x12\x30\n\x03\x41\x64\x64\x12\x12.SMFSessionRequest\x1a\x13.UPFSessionResponse\"\x00\x62\x06proto3')
)




_SMFSESSIONREQUEST = _descriptor.Descriptor(
  name='SMFSessionRequest',
  full_name='SMFSessionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subscriber_id', full_name='SMFSessionRequest.subscriber_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=62,
)


_UPFSESSIONRESPONSE = _descriptor.Descriptor(
  name='UPFSessionResponse',
  full_name='UPFSessionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subscriber_id', full_name='UPFSessionResponse.subscriber_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=107,
)

DESCRIPTOR.message_types_by_name['SMFSessionRequest'] = _SMFSESSIONREQUEST
DESCRIPTOR.message_types_by_name['UPFSessionResponse'] = _UPFSESSIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SMFSessionRequest = _reflection.GeneratedProtocolMessageType('SMFSessionRequest', (_message.Message,), dict(
  DESCRIPTOR = _SMFSESSIONREQUEST,
  __module__ = 'sessionset_pb2'
  # @@protoc_insertion_point(class_scope:SMFSessionRequest)
  ))
_sym_db.RegisterMessage(SMFSessionRequest)

UPFSessionResponse = _reflection.GeneratedProtocolMessageType('UPFSessionResponse', (_message.Message,), dict(
  DESCRIPTOR = _UPFSESSIONRESPONSE,
  __module__ = 'sessionset_pb2'
  # @@protoc_insertion_point(class_scope:UPFSessionResponse)
  ))
_sym_db.RegisterMessage(UPFSessionResponse)



_PIPELINED = _descriptor.ServiceDescriptor(
  name='Pipelined',
  full_name='Pipelined',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=109,
  serialized_end=170,
  methods=[
  _descriptor.MethodDescriptor(
    name='Add',
    full_name='Pipelined.Add',
    index=0,
    containing_service=None,
    input_type=_SMFSESSIONREQUEST,
    output_type=_UPFSESSIONRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PIPELINED)

DESCRIPTOR.services_by_name['Pipelined'] = _PIPELINED

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class PipelinedStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.Add = channel.unary_unary(
          '/Pipelined/Add',
          request_serializer=SMFSessionRequest.SerializeToString,
          response_deserializer=UPFSessionResponse.FromString,
          )


  class PipelinedServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def Add(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_PipelinedServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Add': grpc.unary_unary_rpc_method_handler(
            servicer.Add,
            request_deserializer=SMFSessionRequest.FromString,
            response_serializer=UPFSessionResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'Pipelined', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaPipelinedServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def Add(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaPipelinedStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def Add(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    Add.future = None


  def beta_create_Pipelined_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('Pipelined', 'Add'): SMFSessionRequest.FromString,
    }
    response_serializers = {
      ('Pipelined', 'Add'): UPFSessionResponse.SerializeToString,
    }
    method_implementations = {
      ('Pipelined', 'Add'): face_utilities.unary_unary_inline(servicer.Add),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Pipelined_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('Pipelined', 'Add'): SMFSessionRequest.SerializeToString,
    }
    response_deserializers = {
      ('Pipelined', 'Add'): UPFSessionResponse.FromString,
    }
    cardinalities = {
      'Add': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'Pipelined', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
