# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import sessionset_pb2 as sessionset__pb2


class PipelinedStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Add = channel.unary_unary(
        '/Pipelined/Add',
        request_serializer=sessionset__pb2.SMFSessionRequest.SerializeToString,
        response_deserializer=sessionset__pb2.UPFSessionResponse.FromString,
        )


class PipelinedServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Add(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PipelinedServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Add': grpc.unary_unary_rpc_method_handler(
          servicer.Add,
          request_deserializer=sessionset__pb2.SMFSessionRequest.FromString,
          response_serializer=sessionset__pb2.UPFSessionResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Pipelined', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
